connector:
  name: nofarb account level repo
  identifier: nofarb_account_level_repo
  description:
  orgIdentifier: default
  projectIdentifier: Product_Demos_CIE
  type: Github
  spec:
    url: https://github.com/nofarb/whatever
    validationRepo: HelloTemplates
    authentication:
      type: Http
      spec:
        type: UsernamePassword
        spec:
          username: nofarb
          passwordRef: account.nofar_github_token
    apiAccess:
      type: Token
      spec:
        tokenRef: account.nofar_github_token
    type: Repo
